import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        cargoiq: {
          bg: '#F1F4F8',
          navy: '#1A2332',
          panel: '#141B29',
          deep: '#0F1620',
          gold: '#B8860B',
          goldHover: '#D4922B',
          goldLight: '#D4A017',
          green: '#16A34A',
          red: '#DC2626',
          fg: '#F1F4F8',
          muted: '#9AA7B8',
          textPrimary: '#0D1B2A',
          textSecondary: '#4A5568',
          border: '#E2E8F0',
          warning: '#D97706',
          canvas: '#F1F4F8',
          subtle: 'rgba(255, 255, 255, 0.08)',
        },
        sentinel: {
          bg: '#FFFFFF',
          card: '#FFFFFF',
          text: '#101318',
          counterRed: '#D92D20',
          counterGreen: '#027A48',
          counterBlue: '#175CD3',
        },
        hull: '#FFFFFF',
        panel: '#F6F7F9',
        elevated: '#FFFFFF',
        'border-subtle': '#E4E7EC',
        'cargo-gold': '#C83A12',
        'iq-orange': '#F2451C',
        'risk-red': '#D92D20',
        'success-green': '#027A48',
        surface: '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F6F7F9',
        'surface-container': '#F9FAFB',
        'surface-container-high': '#F6F7F9',
        'surface-container-highest': '#F2F4F7',
        'on-surface': '#101318',
        'on-surface-variant': '#5B6573',
        outline: '#9AA4B2',
        'outline-variant': '#E4E7EC',
        primary: '#C83A12',
        'primary-container': '#C83A12',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#7E2410',
        secondary: '#F2451C',
        'secondary-container': '#C25300',
        tertiary: '#175CD3',
        error: '#D92D20',
        'error-container': '#FEF3F2',
        success: '#027A48',
        warn: '#B54708',
        info: '#175CD3',
        civic: {
          page: '#FFFFFF',
          panel: '#F6F7F9',
          card: '#FFFFFF',
          border: '#E4E7EC',
          'border-strong': '#D0D5DD',
          text: '#101318',
          muted: '#5B6573',
          'nav-text': '#344054',
          zebra: '#F9FAFB',
        },
      },
      fontFamily: {
        inter: ['var(--font-inter)', 'Arial', 'Helvetica', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        'display-lg': ['var(--font-display-lg)', 'Space Grotesk', 'sans-serif'],
        'headline-lg': ['var(--font-display-lg)', 'Space Grotesk', 'sans-serif'],
        'headline-md': ['var(--font-display-lg)', 'Space Grotesk', 'sans-serif'],
        'label-caps': ['var(--font-body-md)', 'IBM Plex Sans', 'sans-serif'],
        'body-md': ['var(--font-body-md)', 'IBM Plex Sans', 'sans-serif'],
        'body-lg': ['var(--font-body-md)', 'IBM Plex Sans', 'sans-serif'],
        'data-tabular': ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-tabular': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '20px',
        'margin-page': '24px',
        'grid-columns': '12',
        'sidebar-width': '260px',
        gutter: '16px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'count-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
