import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        cargoiq: {
          bg: '#F1F4F8',
          navy: '#1A2332',
          panel: '#141B29',
          deep: '#0F1620',
          gold: '#B8860B',
          goldHover: '#D4922B',
          goldLight: '#D4A017',
          green: '#16A34A',
          red: '#DC2626',
          fg: '#F1F4F8',
          muted: '#9AA7B8',
          textPrimary: '#0D1B2A',
          textSecondary: '#4A5568',
          border: '#E2E8F0',
          warning: '#D97706',
          canvas: '#F1F4F8',
          subtle: 'rgba(255, 255, 255, 0.08)',
        },
        sentinel: {
          bg: '#020817',
          card: '#0F172A',
          text: '#F8FAFC',
          counterRed: '#EF4444',
          counterGreen: '#22C55E',
          counterBlue: '#3B82F6',
        },
        hull: '#0A0E13',
        panel: '#12181F',
        elevated: '#161D26',
        'border-subtle': '#1E2733',
        'cargo-gold': '#E8B84B',
        'iq-orange': '#E26A1E',
        'risk-red': '#E5484D',
        'success-green': '#2FBF71',
        surface: '#101419',
        'surface-container-lowest': '#0a0e13',
        'surface-container-low': '#181c21',
        'surface-container': '#1c2025',
        'surface-container-high': '#262a30',
        'surface-container-highest': '#31353b',
        'on-surface': '#e0e2ea',
        'on-surface-variant': '#d2c5b0',
        outline: '#9b8f7c',
        'outline-variant': '#4e4636',
        primary: '#ffd57e',
        'primary-container': '#e8b84b',
        'on-primary': '#402d00',
        'on-primary-container': '#644900',
        secondary: '#ffb691',
        'secondary-container': '#c25300',
        tertiary: '#c4dcff',
        error: '#E5484D',
        'error-container': '#93000a',
        success: '#2FBF71',
      },
      fontFamily: {
        inter: ['var(--font-inter)', 'Arial', 'Helvetica', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['IBM Plex Sans', 'sans-serif'],
        'body-md': ['IBM Plex Sans', 'sans-serif'],
        'body-lg': ['IBM Plex Sans', 'sans-serif'],
        'data-tabular': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-tabular': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '20px',
        'margin-page': '24px',
        'grid-columns': '12',
        'sidebar-width': '260px',
        gutter: '16px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'count-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
