import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        cargoiq: {
          bg: '#F1F4F8',
          navy: '#1A2332',
          panel: '#141B29',
          deep: '#0F1620',
          gold: '#B8860B',
          goldHover: '#D4922B',
          goldLight: '#D4A017',
          green: '#16A34A',
          red: '#DC2626',
          fg: '#F1F4F8',
          muted: '#9AA7B8',
          textPrimary: '#0D1B2A',
          textSecondary: '#4A5568',
          border: '#E2E8F0',
          warning: '#D97706',
          canvas: '#F1F4F8',
          subtle: 'rgba(255, 255, 255, 0.08)',
        },
        sentinel: {
          bg: '#FFFFFF',
          card: '#FFFFFF',
          text: '#101318',
          counterRed: '#D92D20',
          counterGreen: '#027A48',
          counterBlue: '#175CD3',
        },
        hull: 'var(--hull)',
        panel: 'var(--panel)',
        elevated: 'var(--elevated)',
        'border-subtle': 'var(--border-subtle)',
        'cargo-gold': 'var(--cargo-gold)',
        'iq-orange': 'var(--iq-orange)',
        'risk-red': 'var(--risk-red)',
        'success-green': 'var(--success-green)',
        surface: 'var(--surface)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary': 'var(--on-primary)',
        'on-primary-container': 'var(--on-primary-container)',
        secondary: 'var(--secondary)',
        'secondary-container': 'var(--secondary-container)',
        tertiary: 'var(--tertiary)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',
        success: 'var(--success)',
        warn: 'var(--warn)',
        info: 'var(--info)',
        civic: {
          page: 'var(--background)',
          panel: 'var(--surface)',
          card: 'var(--surface-container)',
          border: 'var(--border-subtle)',
          'border-strong': 'var(--outline)',
          text: 'var(--on-surface)',
          muted: 'var(--on-surface-variant)',
          'nav-text': 'var(--on-surface-variant)',
          zebra: 'var(--zebra)',
        },
      },
      fontFamily: {
        inter: ['var(--font-inter)', 'Arial', 'Helvetica', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        'display-lg': ['var(--font-display-lg)', 'Space Grotesk', 'sans-serif'],
        'headline-lg': ['var(--font-display-lg)', 'Space Grotesk', 'sans-serif'],
        'headline-md': ['var(--font-display-lg)', 'Space Grotesk', 'sans-serif'],
        'label-caps': ['var(--font-body-md)', 'IBM Plex Sans', 'sans-serif'],
        'body-md': ['var(--font-body-md)', 'IBM Plex Sans', 'sans-serif'],
        'body-lg': ['var(--font-body-md)', 'IBM Plex Sans', 'sans-serif'],
        'data-tabular': ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-tabular': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '20px',
        'margin-page': '24px',
        'grid-columns': '12',
        'sidebar-width': '260px',
        gutter: '16px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'count-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
