'use client';

import React from 'react';
import { TrendingUp, PiggyBank, CheckSquare } from 'lucide-react';

const stats = [
  {
    icon: TrendingUp,
    value: '21.6×',
    label: 'Illustrative ROI',
    description: 'Detected leakage vs. subscription, modelled for a mid-size operation. Your real multiple comes from your audit.',
  },
  {
    icon: PiggyBank,
    value: 'R14,169',
    label: 'Typical Monthly Leakage (illustrative)',
    description: 'Modelled monthly leakage per mid-size operation. NOT a client result — your audit makes it real.',
  },
  {
    icon: CheckSquare,
    value: '7',
    label: 'Automated Checks Per Document',
    description: 'HS code · valuation · origin · Incoterms · detention · RLA status · personal-liability — every document, every time.',
  },
];

export function ROIStats() {
  return (
    <section className="bg-cargoiq-deep border-y border-cargoiq-subtle py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <p className="text-xs font-semibold text-cargoiq-gold uppercase tracking-[0.2em] mb-3">Proof</p>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-cargoiq-fg mb-4">
            Grounded in real law and real economics — your verified number is next.
          </h2>
          <p className="text-lg text-cargoiq-muted max-w-2xl mx-auto">
            These figures are illustrative benchmarks. The only verified figure we publish is the one your own shadow audit produces.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-cargoiq-subtle">
          {stats.map((stat, index) => (
            <div
              key={index}
              className="bg-cargoiq-panel p-8 md:p-10 text-center"
            >
              <stat.icon className="w-5 h-5 text-cargoiq-gold mx-auto mb-6" />
              <p className="font-mono text-5xl md:text-6xl font-bold text-cargoiq-fg mb-4 tracking-tight">
                {stat.value}
              </p>
              <h3 className="text-sm font-semibold text-cargoiq-muted uppercase tracking-wider mb-2">
                {stat.label}
              </h3>
              <p className="text-xs text-cargoiq-muted/70">
                {stat.description}
              </p>
            </div>
          ))}
        </div>
        <p className="text-center text-xs text-cargoiq-muted/60 max-w-3xl mx-auto mt-8 leading-relaxed">
          Figures on this page are illustrative — modelled from published SARS penalty schedules, the Customs and Excise Act (incl. Section 99(2)), and industry billing-error benchmarks. They are not client results, and we don&apos;t publish fake ones. Your verified figure is generated by your own free shadow audit, line by line, before you pay anything.
        </p>
      </div>
    </section>
  );
}
