'use client';

import React from 'react';
import { TrendingUp, PiggyBank, CheckSquare } from 'lucide-react';

const stats = [
  {
    icon: TrendingUp,
    value: '21.6×',
    label: 'Illustrative ROI',
    description: 'Detected leakage vs. subscription, modelled for a mid-size operation. Your real multiple comes from your audit.',
  },
  {
    icon: PiggyBank,
    value: 'R14,169',
    label: 'Typical Monthly Leakage (illustrative)',
    description: 'Modelled monthly leakage per mid-size operation. NOT a client result — your audit makes it real.',
  },
  {
    icon: CheckSquare,
    value: '7',
    label: 'Automated Checks Per Document',
    description: 'HS code · valuation · origin · Incoterms · detention · RLA status · personal-liability — every document, every time.',
  },
];

export function ROIStats() {
  return (
    <section className="py-20 px-margin-page bg-surface-container-lowest">
      <div className="max-w-7xl mx-auto px-margin-page">
        <div className="text-center mb-16">
          <p className="font-label-caps text-label-caps text-primary uppercase tracking-widest mb-3">Proof</p>
          <h2 className="font-headline-lg text-headline-lg text-on-surface mb-4">
            Grounded in real law and real economics — your verified number is next.
          </h2>
          <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl mx-auto">
            These figures are illustrative benchmarks. The only verified figure we publish is the one your own shadow audit produces.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-gutter bg-surface-container-low">
          {stats.map((stat, index) => (
            <div
              key={index}
              className="bg-surface-container p-8 md:p-10 text-center border-technical"
            >
              <span className="material-symbols-outlined text-primary mx-auto mb-6">{stat.icon === TrendingUp ? 'trending_up' : stat.icon === PiggyBank ? 'payments' : 'verified'}</span>
              <p className="mono text-right text-headline-md text-on-surface mb-4 tracking-tight">{stat.value}</p>
              <h3 className="font-label-caps text-label-caps text-on-surface-variant uppercase tracking-wider mb-2">
                {stat.label}
              </h3>
              <p className="text-xs text-on-surface-variant/70">
                {stat.description}
              </p>
            </div>
          ))}
        </div>
        <p className="text-center text-xs text-outline mono text-right uppercase tracking-tighter mt-8">
          Figures on this page are illustrative — modelled from published SARS penalty schedules, the Customs and Excise Act (incl. Section 99(2)), and industry billing-error benchmarks. They are not client results, and we do not publish fake ones. Your verified figure is generated by your own free shadow audit, line by line, before you pay anything.
        </p>
      </div>
    </section>
  );
}
